# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/xavuka1020/ed176fc5aa3f68ff3fec2f0a886e0a1b/untitled15.ipynb
"""

print ('●'*40)
print ('BEM VINDO,SOMOS O GRUPO 3 E VAMOS APRESENTAR ALGUMAS SOLUCOES EM RH')
print ('●'*40)
from datetime import date
colab = list()
dados = dict()
ano = date.today().year
print ('O que você deseja fazer')
print ('1 - incluir funcionarios')
print ('2 - pesquisa de funcionario')
print ('3 - calcular demissão')
print ('4 - consultar férias')
print ('5 - incluir faltas')
print ('6 - Pesquisa de satisfacao')
print ('7 - banco de curriculos')
print ('8 - departamentos')
print ('9 - 13° salario')
print ('10 - atualizar cadastro')
print ('11 - Calculo de bonus')

escolha = insert = int(input('escolha uma opçao: '))
print ('='*40)
if escolha == 1:
 
  while True:
    colab = dados.copy()
    dados.clear()
    dados['nome'] = str(input('Nome: '))
    dados['nascimento'] = int(input('Ano de nascimento: '))
    dados['Idade'] = ano - dados['nascimento']
    dados['parar'] = str(input('Deseja cadastrar outro funcionario ?'))

    if dados['parar'] == 'nao':
       break
    else:
        print ('='*40)
        print ('proximo funcionario')
        print ('='*40)
print ('='*40)
print ('      o que você deseja fazer      ')
print ('1 - incluir funcionarios')
print ('2 - pesquisa de funcionario')
print ('3 - calcular demissão')
print ('4 - consultar férias')
print ('5 - incluir faltas')  
print ('6 - Pesquisa de satisfacao')
print ('7 - banco de curriculos')
print ('8 - departamentos')
print ('9 - 13° salario')
print ('10 - atualizar cadastro')
print ('11 - Calculo de bonus')

 
escolha = insert = int(input('escolha uma opçao: '))
print ('='*40)
if escolha == 2:
    pesquisa = insert = str(input('qual o nome do funcionario: '))
if pesquisa == colab:
    print (colab)
else:
      print ('='*40)
print ('      o que você deseja fazer      ')
print ('1 - incluir funcionarios')
print ('2 - pesquisa de funcionario')
print ('3 - calcular demissão')
print ('4 - consultar férias')
print ('5 - incluir faltas')  
print ('6 - Pesquisa de satisfacao')
print ('7 - banco de curriculos')
print ('8 - departamentos')
print ('9 - 13° salario')
print ('10 - atualizar cadastro')
print ('11 - Calculo de bonus')

escolha = insert = int(input('escolha uma opçao: '))
print ('='*40)
if escolha == 3:
    pesquisa = insert = str(input('qual o nome do funcionario: '))
    sal = insert = int(input('qual o salario'))
    temp = insert = int(input('quantos meses tem na empresa '))
    fgts = insert = int(input('valor do fgts'))
    ferias = insert = int(input('quantas ferias vencidas'))
    print (' A empresa tera de pagar o valor de R$',sal+ferias*sal+sal+fgts*30/100)